//go:build !ignore_autogenerated

// Code generated by controller-gen (or its hand-written equivalent). DO NOT
// EDIT — regenerate via `make generate` once controller-gen is wired into
// the build. The methods below are the standard DeepCopy / DeepCopyInto /
// DeepCopyObject set that K8s runtime.Object requires for any CRD.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// -----------------------------------------------------------------------
// KVCacheCluster
// -----------------------------------------------------------------------

func (in *KVCacheCluster) DeepCopyInto(out *KVCacheCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KVCacheCluster) DeepCopy() *KVCacheCluster {
	if in == nil {
		return nil
	}
	out := new(KVCacheCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *KVCacheCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KVCacheClusterList) DeepCopyInto(out *KVCacheClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KVCacheCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KVCacheClusterList) DeepCopy() *KVCacheClusterList {
	if in == nil {
		return nil
	}
	out := new(KVCacheClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *KVCacheClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KVCacheClusterSpec) DeepCopyInto(out *KVCacheClusterSpec) {
	*out = *in
	out.Tier = in.Tier // all scalar fields, value copy is sufficient
	if in.EtcdEndpoints != nil {
		out.EtcdEndpoints = make([]string, len(in.EtcdEndpoints))
		copy(out.EtcdEndpoints, in.EtcdEndpoints)
	}
	if in.Etcd != nil {
		out.Etcd = new(EtcdSpec)
		*out.Etcd = *in.Etcd
	}
	if in.ControlPlane != nil {
		out.ControlPlane = new(ControlPlaneSpec)
		*out.ControlPlane = *in.ControlPlane
	}
	if in.AlluxioBinding != nil {
		out.AlluxioBinding = new(AlluxioBinding)
		*out.AlluxioBinding = *in.AlluxioBinding
	}
	in.NodeResources.DeepCopyInto(&out.NodeResources)
}

func (in *KVCacheClusterSpec) DeepCopy() *KVCacheClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KVCacheClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KVCacheClusterStatus) DeepCopyInto(out *KVCacheClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.MtlsCertNotAfter != nil {
		out.MtlsCertNotAfter = in.MtlsCertNotAfter.DeepCopy()
	}
}

func (in *KVCacheClusterStatus) DeepCopy() *KVCacheClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KVCacheClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// -----------------------------------------------------------------------
// KVCacheTenant
// -----------------------------------------------------------------------

func (in *KVCacheTenant) DeepCopyInto(out *KVCacheTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KVCacheTenant) DeepCopy() *KVCacheTenant {
	if in == nil {
		return nil
	}
	out := new(KVCacheTenant)
	in.DeepCopyInto(out)
	return out
}

func (in *KVCacheTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KVCacheTenantList) DeepCopyInto(out *KVCacheTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KVCacheTenant, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KVCacheTenantList) DeepCopy() *KVCacheTenantList {
	if in == nil {
		return nil
	}
	out := new(KVCacheTenantList)
	in.DeepCopyInto(out)
	return out
}

func (in *KVCacheTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KVCacheTenantStatus) DeepCopyInto(out *KVCacheTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *KVCacheTenantStatus) DeepCopy() *KVCacheTenantStatus {
	if in == nil {
		return nil
	}
	out := new(KVCacheTenantStatus)
	in.DeepCopyInto(out)
	return out
}
